export const officialAwardCategories = [
    "Best Content Creator of the Year",
    "Best DJ of the Year",
    "Song of the Year",
    "Best Dancer of the Year",
    "Best Male PR Content Creator of the Year",
    "Best Female PR Content Creator of the Year",
    "Visual Artist of the Year",
    "Music Artist of the Year",
    "Photographer/Videographer of the Year",
    "Beauty and Aesthetics Professional of the Year",
    "Entrepreneur of the Year",
    "Best Fashion Designer of the Year",
    "Public Figure of the Year",
];
